version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      - FRONT_URL=http://localhost:3000
    depends_on:
      - db
  db:
    image: sqlite:3
    volumes:
      - ./db:/db
